# Generated by Django 5.2.14 on 2026-05-26 20:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0003_user_two_factor_enabled_user_two_factor_secret'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='two_factor_method',
            field=models.CharField(blank=True, choices=[('totp', '验证器 App'), ('email', '邮件验证')], default='', max_length=10, verbose_name='二次验证方式'),
        ),
    ]
